namespace fe
{
    public enum SourceType
    {
        AMAZONS3,
        BOX,
        BOX_ENTERPRISE,
        BOX_ENTERPRISE2,
        CATALOG,
        CONFLUENCE,
        CONFLUENCE2,
        CONFLUENCE2_HOSTED,
        CUSTOM,
        DATABASE,
        DROPBOX,
        DROPBOX_FOR_BUSINESS,
        EXCHANGE,
        EXCHANGE_ENTERPRISE,
        FILE,
        GMAIL,
        GMAIL_DOMAIN_WIDE,
        GMAIL_SINGLE_USER,
        GENERIC_REST,
        GOOGLE_DRIVE_DOMAIN_WIDE,
        GOOGLE_DRIVE_SINGLE_USER,
        JIRA2,
        JIRA2_HOSTED,
        JIVE,
        JIVE_HOSTED,
        LITHIUM,
        MICROSOFT_DYNAMICS,
        ONEDRIVE_FOR_BUSINESS,
        OPENTEXT_CONTENT_SERVER,
        PUSH,
        RSS,
        SALESFORCE,
        SERVICENOW,
        SHAREPOINT,
        SHAREPOINT_ONLINE,
        SHAREPOINT_ONLINE2,
        SITECORE,
        SITEMAP,
        TWITTER2,
        WEB2,
        YOUTUBE,
        ZENDESK
    }
    //    AMAZONS3("Connector.AmazonS3"),
    //    BOX("Connector.Box"),
    //    BOX_ENTERPRISE("Connector.Box"),
    //    BOX_ENTERPRISE2("Connector.Box"),
    //    CATALOG("Catalog"), // "Catalog" is not a real crawler instance type, but we need it to translate the source back to a model, no crawler node will be spawned
    //    CONFLUENCE("Connector.Confluence"),
    //    CONFLUENCE2("Connector.Confluence2"),
    //    CONFLUENCE2_HOSTED("Connector.Confluence2"),
    //    CUSTOM,
    //    DATABASE("Connector.Database"),
    //    DROPBOX("Connector.Dropbox"),
    //    DROPBOX_FOR_BUSINESS("Connector.DropboxforBusiness"),
    //    EXCHANGE("Connector.Exchange"),
    //    EXCHANGE_ENTERPRISE("Connector.Exchange"),
    //    FILE("Connector.FileSystem"),
    //    GMAIL("Connector.Imap"),
    //    GMAIL_DOMAIN_WIDE("Connector.GmailGoogleApps"),
    //    GMAIL_SINGLE_USER("Connector.GmailSingleUser"),
    //    GENERIC_REST("Connector.GenericRest"),
    //    GOOGLE_DRIVE_DOMAIN_WIDE("Connector.GoogleDriveCompactGoogleApps"),
    //    GOOGLE_DRIVE_SINGLE_USER("Connector.GoogleDriveSingleUser"),
    //    JIRA2("Connector.Jira2"),
    //    JIRA2_HOSTED("Connector.Jira2"),
    //    JIVE("Connector.Jive"),
    //    JIVE_HOSTED("Connector.Jive"),
    //    LITHIUM("Connector.Lithium"),
    //    MICROSOFT_DYNAMICS("Connector.DynamicsCRM"),
    //    ONEDRIVE_FOR_BUSINESS("Connector.OneDriveforBusiness"),
    //    PUSH("Push"), // "Push" is not a real crawler instance type, but we need it to translate the source back to a model, no crawler node will be spawned
    //    RSS("Connector.RSS"),
    //    SALESFORCE("Connector.Salesforce2"),
    //    SERVICENOW("Connector.ServiceNow"),
    //    SHAREPOINT_ONLINE("Connector.SharePoint"),
    //    SHAREPOINT_ONLINE2("Connector.SharePointOnline"),
    //    SITECORE("Connector.Sitecore2"),
    //    SITEMAP("Connector.Sitemap"),
    //    TWITTER2("Connector.Twitter2"),
    //    WEB2("Connector.Web2"),
    //    YOUTUBE("Connector.YouTube"),
    //    ZENDESK("Connector.Zendesk");
}
